### ISSUE TITLE
cannot log

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/git_proc_commit#10]
I encountered this error:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/handlers.py", line 934, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/handlers.py", line 855, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/handlers.py", line 937, in emit
    self._connect_unixsocket(self.address)
  File "/usr/local/lib/python3.7/logging/handlers.py", line 866, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/local/libexec/freshports/git-to-freshports-xml.py", line 163, in <module>
    main()
  File "/usr/local/libexec/freshports/git-to-freshports-xml.py", line 108, in main
    log.info(f"Processing commit '{commit.message.splitlines()[0]}'")
Message: "Processing commit 'games/freeminer: unbreak after r540853'"
Arguments: ()

```

**Comment by dlangille** [comment]
Fix:

Change: `SYSLOG_ADDRESS = '/dev/log'  # Or UDP socket like ('1.2.3.4', 514)`
to: SYSLOG_ADDRESS  = '/var/run/log'  # Or UDP socket like ('1.2.3.4', 514)
