### ISSUE TITLE
code processing is expecting UTF-8 - perhaps it should be ASCII

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/git_proc_commit#44]
re https://github.com/FreshPorts/freshports/issues/379

It can be reproduced with:

```
[dev-ingress01 dan ~/tmp] % /usr/local/libexec/freshports/git-to-freshports-xml.py --repo ports --path ~/src/FreeBSD/ports --branch 2020Q1 -s bc0620b2474bc31161f4a20388e28c0d91c8a92c --spooling ~/tmp/spooling --output ~/tmp/incoming  --verbose                                     
Traceback (most recent call last):
  File "/usr/local/libexec/freshports/git-to-freshports-xml.py", line 255, in <module>
    main()
  File "/usr/local/libexec/freshports/git-to-freshports-xml.py", line 195, in main
    text.text = commit.message.strip()
  File "src/lxml/etree.pyx", line 1041, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 748, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 736, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1541, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
[dev-ingress01 dan ~/tmp] %                                                                                                                                                19:05:28
```

_Originally posted by @dlangille in https://github.com/FreshPorts/freshports/issues/379#issuecomment-1209769679_

**Comment by dlangille** [comment]
@skozlov404 are you available to investigate this one? Even if you can give me an idea of where to look, I can follow up.

Best wishes.

**Comment by dlangille** [comment]
I have a working solution taken from https://tousu.in/qa/?qa=986000/xml-filtering-out-certain-bytes-in-python

```
[dev-ingress01 dan ~/tmp] % diff -ruN /usr/local/libexec/freshports/git-to-freshports-xml.py ~/tmp/git-to-freshports-xml.py                                                20:40:16
--- /usr/local/libexec/freshports/git-to-freshports-xml.py	2022-07-25 04:24:26.000000000 +0000
+++ /usr/home/dan/tmp/git-to-freshports-xml.py	2022-08-09 20:40:11.896528000 +0000
@@ -134,6 +134,16 @@
     return list(reversed(result))
 
 
+def valid_xml_char_ordinal(c):
+    codepoint = ord(c)
+    # conditions ordered by presumed frequency
+    return (
+        0x20 <= codepoint <= 0xD7FF or
+        codepoint in (0x9, 0xA, 0xD) or
+        0xE000 <= codepoint <= 0xFFFD or
+        0x10000 <= codepoint <= 0x10FFFF
+        )
+    
 def main():
     config = get_config()
     configure_logging(config['log_level'], config['log_destination'])
@@ -192,7 +202,7 @@
 
         log.debug("Writing commit message")
         text = ET.SubElement(update, 'LOG')
-        text.text = commit.message.strip()
+        text.text = ''.join(c for c in commit.message.strip() if valid_xml_char_ordinal(c))
 
         log.debug("Writing author")
         people = ET.SubElement(update, 'PEOPLE')
[dev-ingress01 dan ~/tmp] %                                                                                                                                                20:40:22
```

**Comment by skozlov404** [comment]
I've seen multiple solutions like this, but I expect it to be brittle. Can't guarantee that this code a) removes all the illegal chars b) doesn't remove any legal by accident. I'm trying to find a better solution.

**Comment by skozlov404** [comment]
I've looked more and it doesn't seem there's an lxml-blessed solution for this, so I guess your fix is the way to go. There might be some performance implications, let me know if you start having trouble with it.

**Comment by dlangille** [comment]
The major places which have non-standard characters are commit messages and `pkg-descr`.

I think this code translates each character at a time, so yes, that might not be optimal.
